name: CI for web-php-bdd

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: raparisonbryan/TP_github_runners
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Compose
        run: |
          docker-compose up -d
        working-directory: ./docker-compose.yml

      - name: Test web page
        run: |
          curl -f http://localhost:8080 || exit 1

      - name: Stop Docker Compose
        run: |
          docker-compose down
        working-directory: ./docker-compose.yml
